### ISSUE TITLE
POC requirements

### ISSUE THREAD

**Issue by Danwhy** [cul-2016/forum#1]
### Initial requirements for Study Planner proof of concept/MVP

- [ ] Initial setup of NodeBB
- [ ] Use Quodl logins as forum logins
- [ ] Creating Modules as Categories accessible only to module members
- [ ] Automatically giving lecturers privileges on modules they own
- [ ] Auto generating posts from Quodl (Stats from last week etc.)
